export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const POST_PRODUCT = "POST_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const POST_CATEGORY = "POST_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const GET_ORDERS = "GET_ORDERS"
export const ADD_TO_CART = "ADD_TO_CART";
export const GET_PRODUCT_CART = "GET_PRODUCT_CART";
export const GET_SPECIFIC_ORDER = "GET_SPECIFIC_ORDER";
export const UPDATE_STATE_ORDER = "UPDATE_STATE_ORDER"

export const POST_USER = "POST_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";
export const GET_USER = "GET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_PROMOTE = "UPDATE_PROMOTE";
export const POST_RESERT_PASSWORD = "POST_RESERT_PASSWORD";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const ALL_ORDERS_USER = "ALL_ORDERS_USER"
export const STATES_ORDERS = "STATES_ORDERS"

export const ADD_TO_CART_LOCALSTORAGE = "ADD_TO_CART_LOCALSTORAGE";
export const GET_PRODUCT_CART_LOCALSTORAGE = "GET_PRODUCT_CART_LOCALSTORAGE";
export const DELETE_TOTAL_CART = "DELETE_TOTAL_CART";
export const DELETE_ITEMS_CART = "DELETE_ITEMS_CART";
export const DELETE_CART_LS = "DELETE_CART_LS";
export const DELETE_ITEM_LC = "DELETE_ITEM_LC";
export const UPDATE_COUNT_PRODUCT = "UPDATE_COUNT_PRODUCT";

export const GET_PRODUCTS_STATE_COMPLETE = "GET_PRODUCTS_STATE_COMPLETE";
export const GET_ALL_REVIEWS_USER = 'GET_ALL_REVIEWS_USER';
export const ADD_REVIEW = 'ADD_REVIEW';
export const EDIT_REVIEW = ' EDIT_REVIEW';
export const DELETE_REVIEW = ' DELETE_REVIEW';
export const GET_ALL_REVIEW_PRODUCT = 'GET_ALL_REVIEW_PRODUCT';
export const POST_USER_FAILED = 'POST_USER_FAILED';


export const MELI_CART = "MELI_CART"
export const ADDRESS_ORDER = "ADDRESS_ORDER"

export const ADD_DISCOUNT= "ADD_DISCOUNT"

export const GET_DISCOUNT= "GET_DISCOUNT"
export const EDIT_DISCOUNT= "EDIT_DISCOUNT"
export const GET_DISCOUNT_ACTIVE ="GET_DISCOUNT_ACTIVE"
